name: mybengkel
description: "Aplikasi Manajemen Bengkel"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase - Versi Stabil & Kompatibel
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # State Management
  provider: ^6.1.1
  # UI Components
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  # Charts
  fl_chart: ^0.66.2
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  printing: ^5.14.2
  pdf: ^3.10.7
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2

dependency_overrides:
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.17.8
  firebase_auth_platform_interface: ^7.2.5
  cloud_firestore: ^4.15.8
  cloud_firestore_platform_interface: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
